---
  - hosts: all
    gather_facts: no
    tasks:
      - name: Upgrade all packages in RedHat-based machines
        yum: name=* state=latest

      - name: Reboot the server
        command: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
        async: 1
        poll: 0
        ignore_errors: true
        become: true


      - name: Wait 300 seconds for port 22 to become open
        local_action:
          module: wait_for
            port=22
            delay=10
            timeout=300

      - name: Check the Uptime of the servers
        shell: "uptime"
        register: Uptime

      - debug: var=Uptime
